config/routes.rb
Scheduler::Application.routes.draw do
  devise_for :users

  resources :employees
  resources :roles
  resources :shifts
  resources :days
  resources :schedules

  root :to => 'pages#dashboard'

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  # Have to make these attributes accessible to insert into join table (employments)
  # Have to have :role_ids to assign roles to an employee 
  attr_accessible :first_name, :last_name, :role_ids, :shift_ids
  #:role_ids, :employee_id,:shift_ids
  
  validates :first_name,  :presence => true
  validates :last_name,   :presence => true

  has_many  :workdays
  has_many  :shifts, :through => :workdays

  has_many  :employments
  has_many  :roles, :through => :employments

 
  def self.elgible_per_shift(shifts)
    
    shift_roles = shifts.map(&:role_ids) 
    shift_names = shifts.map(&:name)
    shift_start_end_times = shifts.map {|shift| [shift.time_start, shift.time_end]}

    elgible_employees = shift_roles.inject([]) do |result, shift_role|
      employees_shuffled = self.elgible_for_shift_by_role( shift_role ).shuffle!
      result << [ employees_shuffled, employees_shuffled[0] ]
      result
    end

    employees_for_shift = shift_names.zip(shift_start_end_times, elgible_employees)

    # Start of code to create nested array that does not have employees double
    # scheduled according to time
    #scheduled_employee = employees_for_shift.map {|shift| shift[2][1] }
    #scheduled_more_than_once = scheduled_employee.map {|employee| employee if scheduled_employee.count(employee) > 1 }.compact.uniq
    #
    #test = []

    #scheduled_employee.each do |employee|
    #  if scheduled_employee.count( employee ) >= 2 
    #    test << scheduled_employee.index( employee.to_s )
    #  end
    #end

    #debugger

    #employees_for_shift
    

  end

  # web-friendly name
  def full_name
    [ self.first_name, self.last_name ].join(" ")
  end

  def days_worked
    self.workdays
  end
  
  private

    # Used as a helper method for self.elgible_per_shift. Returns an array of
    # employees that are elgible to work that shift according to their assigned roles
    def self.elgible_for_shift_by_role(role_ids_for_shift)
      joins(:roles).
      where("roles.id IN(?)", role_ids_for_shift ).
      collect(&:full_name).uniq.sort
    end


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # redirect to root unless user is signed_in
  before_filter :show_page?

  respond_to :html, :xml, :json

  def index
    # To order the employees by last_name you can remove '.all'
    # and add '.order()'.  The '.all' is implied
    @employees = Employee.order("last_name asc")
    
    # rendering html, xml, json
    respond_with(@employees)
  end

  # Individual employees
  def show
    @employee = Employee.find(params[:id])
  end

  # The html form for creating a new employee
  def new 
    # ':employee' get the nested dictionary (i.e. all the form values)
    @employee = Employee.new
  end

  # POST => database 
  def create 
    # Saving the ':employee' and all the form values, which is in a nested dictionary
    @employee = Employee.new(params[:employee])

    if @employee.save
      flash[:success] = "Employee #{@employee.full_name} was created!"

      # Redirect to employee index
      redirect_to employees_url
    else
      flash[:failure] = "Employee NOT created!"
      render :action => 'new'

      # Why not something like this instead of " render 'new' "?
      #render new_employee_url 
    end
  end

  # PUT => database
  def update
    
    # If employee was submitted with 'no' roles (i.e. no checkboxes where
    # checked) then set employee.role_ids to empty array
    params[:employee][:role_ids] ||= []

    # Find the same employee that was used in the 'edit' action. 
    @employee = Employee.find(params[:id])

    # If the saving of the employee is successfull
    if @employee.update_attributes(params[:employee])
      flash[:success] = "Employee #{@employee.full_name} was updated"
      redirect_to employees_url
    else
      flash[:failure] = "Employee was NOT updated"
      render 'edit'
    end
  end

  # Used in the html form.
  def edit
    @employee = Employee.find(params[:id])
  end

  # DELETE => database
  def destroy
    employee = Employee.find(params[:id]).destroy
    flash[:success] = "Employee #{employee.full_name} was destroyed."
    redirect_to employees_url
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for @employee do |f| %>
  
  <%= render 'shared/errormessages', :object => f.object %>

  <div>
    <%= f.label "First Name: " %>
    <%= f.text_field :first_name %><br />
    <%= f.label "Last Name: " %>
    <%= f.text_field :last_name %><br />
    <%= f.label "Role: " %><br />

    <% Role.all.each do |role| %>
      <div>
        <%= check_box_tag 'employee[role_ids][]', role.id, @employee.roles.include?(role) %>
        <%= role.name %>
      </div>
    <% end %>

    <%= f.submit submit_text %>
  </div>

  <p>  
    <%= link_to "Cancel", employees_url  %> 
  </p>

<% end %>

app/views/employees/edit.html.erb
<%= render 'form', :submit_text => 'Update' %>

app/views/employees/index.html.erb
<h1>Employees</h1>

<table>
  <% @employees.each do |employee| %>
    <tr>
      <td>
        <%= link_to employee.full_name, employee %>
      </td>
      <td>
        <%= link_to "delete", employee, :method => :delete, 
          :confirm => "Are you sure you want to delete #{employee.full_name}?", :title => "Delete #{employee.full_name}"%>    
      </td>
      <td>
        <%= link_to "edit", edit_employee_path(employee) %>    
      </td>
    </tr>
  <% end %>
</table>

app/views/employees/new.html.erb
<%= render 'form', :submit_text => 'Create' %>

app/views/employees/show.html.erb
<p>First Name: <%= @employee.full_name %> </p>

<p>
  <%= link_to "Delete", @employee, :method => :delete, 
      :confirm => "Are you sure you want to delete #{ @employee.full_name }?" %> |
  <%= link_to "Edit", edit_employee_url(@employee) %> |
  <%= link_to "All Employees", employees_path %>
</p>

<br />
<p>Roles: </p>
<ul>  
  <% @employee.roles.each do |role| %> 
    <li> <%=  role.name %> </li>
  <% end %>
</ul>

<br />

<p>Days worked:</p>

<ul>
  <% @employee.days_worked.each do |workday| %>
  <li> <%= workday.schedule.date %> </li>
  <% end %>
</ul>