config/routes.rb
Scheduler::Application.routes.draw do
  devise_for :users

  resources :employees
  resources :roles
  resources :shifts
  resources :days
  resources :schedules

  root :to => 'pages#dashboard'

end

app/models/shift.rb
class Shift < ActiveRecord::Base

  # Should have to have :employee_ids to assign employees to a shift
  attr_accessible :name, :time_start, :time_end, :employee_ids, :role_ids
  #attr_accessor :day_of_week_template_name

  has_many  :workdays
  has_many  :employees, :through => :workdays

  has_many  :assignments
  has_many  :days, :through => :assignments

  has_many  :shiftroles
  has_many  :roles, :through => :shiftroles

  validates :name, :presence => true,
            :uniqueness => true
  validates :time_start, :presence => true
  validates :time_end, :presence => true

  # Used to display the role names that are elgible to fill a shift. If empty
  # then print custom message
  def roles_assigned_to_shift( for_print )
    self.roles.empty? ? for_print : self.roles.map { |role| role.name }.join(", ") 
  end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController

  # redirect to root unless user is signed_in
  before_filter :show_page?

  def index
    @shifts = Shift.order("name asc")
  end

  # used to generate a html form for new shift
  def new
    @shift = Shift.new
  end

  def create
    @shift = Shift.new(params[:shift])

    if @shift.save
      flash[:success] = "Shift successfully created!"
      redirect_to shifts_url
    else
      flash[:failure] = "Shift NOT created!"
      render :action => 'new'
    end
  end

  def edit
    @shift = Shift.find(params[:id])
  end

  def update
    
    params[:shift] ||= []

    @shift = Shift.find(params[:id])

    if @shift.update_attributes(params[:shift])
      flash[:success] = "Shift was updated"
      redirect_to shifts_url
    else
      flash[:failure] = "Shift was NOT updated"
      render 'edit'
    end
  end

  def destroy
    puts '*'*80
    puts '*'*80

    shift = Shift.find(params[:id]).destroy
    flash[:success] = "Shift was destroyed"
    redirect_to shifts_path
    #@shift.destroy
    #redirect_to shifts_path, :flash => { :success => "Shift was destroyed" }
  end

  # Individual employees
  #def show
  #  @shift = Shift.find(params[:id])
  #end




end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<%= form_for @shift do |f| %>

  <%= render 'shared/errormessages', :object => f.object %>

  <%= f.label "Shift name" %>
  <%= f.text_field :name %> <br />

  <%= f.label 'Start' %>
  <%= f.time_select :time_start, {:ampm => true, :minute_step => 15} %> <br />

  <%= f.label 'End' %>
  <%= f.time_select :time_end, {:ampm => true, :minute_step => 15} %> <br />

  <%= f.label "Roles that can fill shift"%> <br />
  
  <% Role.all.each do |role| %>
    <%= check_box_tag 'shift[role_ids][]', role.id, @shift.roles.include?(role) %>
    <%= role.name %>
  <% end %>

  <br />

  <%= f.submit submit_text %>

<% end %>

<p> <%= link_to "Cancel", shifts_url %> </p>

app/views/shifts/index.html.erb
<table>
  <tr>
    <th>Shift Name</th>
    <th>Role</th>
    <td></td>
  </tr>
  <% @shifts.each do |shift| %>
    <tr>
      <td><%= shift.name %><td>
          <td><%= shift.roles_assigned_to_shift "No roles assigned" %><td>
      <td><%= link_to 'delete', shift, :method => :delete,
              :confirm => "Are you sure you want to delete #{ shift.name }?",
              :title => "Delete #{ shift.name }" %>
      </td>
      <td><%= link_to "edit", edit_shift_path(shift) %> </td>
    </tr>
  <% end %>
</table>

app/views/shifts/new.html.erb
<h1>Shifts</h1>

<%= render 'form', :submit_text => 'Create' %>