config/routes.rb
Scheduler::Application.routes.draw do
  devise_for :users

  resources :employees
  resources :roles
  resources :shifts
  resources :days
  resources :schedules

  root :to => 'pages#dashboard'

end

app/models/day.rb
class Day < ActiveRecord::Base
  attr_accessible :name, :assignment_ids, :shift_ids

  has_many  :assignments
  has_many  :shifts, :through => :assignments

  has_many  :schedules

  has_many  :work_days

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
 
  # redirect to root unless user is signed_in
  before_filter :show_page?

  def index
    @days = Day.order("name asc")
  end

  # used to generate a html form for new shift
  def new
    @day = Day.new
  end

  def create
    @day = Day.new(params[:day])

    if @day.save
      flash[:success] = "Day successfully created!"
      redirect_to days_url
    else
      flash[:failure] = "Day NOT created!"
      render :action => 'new'
    end
  end

  def edit
    @day = Day.find(params[:id])
  end

  def update
    
    params[:shift] ||= []

    @day = Day.find(params[:id])

    if @day.update_attributes(params[:day])
      flash[:success] = "Day was updated"
      redirect_to days_url
    else
      flash[:failure] = "Day was NOT updated"
      render 'edit'
    end
  end

  def destroy
    day = Day.find(params[:id]).destroy
    flash[:success] = "Day was destroyed"
    redirect_to days_path
  end



end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_for @day do |f| %>
  
  <%= render 'shared/errormessages', :object => f.object %>

  <div>
    <%= f.label "Name: " %>
    <%= f.text_field :name %><br />

    <% Shift.all.each do |shift| %>
      <div>
        <%= check_box_tag 'day[shift_ids][]', shift.id, @day.shifts.include?(shift) %>
        <%= shift.name %>
      </div>
    <% end %>

    <%= f.submit submit_text %>
  </div>

  <p>  
    <%= link_to "Cancel", days_url  %> 
  </p>

<% end %>

app/views/days/edit.html.erb
<%= render 'form', :submit_text => 'Update' %>

app/views/days/index.html.erb
<table>
  <tr>
    <th>
      Template Day Name
    </th>
    <td>
    </td>
    <td>
    </td>
  </tr>
<% @days.each do |day| %>
  <tr>
    <td> <%= day.name %> </td>
    <td>
        <%= link_to "delete", day, :method => :delete, 
          :confirm => "Are you sure you want to delete #{day.name}?", :title => "Delete #{day.name}"%>    
    </td>
    <td>
        <%= link_to "edit", edit_day_path(day) %>    
    </td>
  </tr>
<% end %>
</table>

app/views/days/new.html.erb
<%= render 'form', :submit_text => 'Create' %>

app/views/days/update.html.erb
<h1>Days#update</h1>
<p>Find me in app/views/days/update.html.erb</p>