config/routes.rb
Scheduler::Application.routes.draw do
  devise_for :users

  resources :employees
  resources :roles
  resources :shifts
  resources :days
  resources :schedules

  root :to => 'pages#dashboard'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :shift_id, :day_id

  belongs_to  :day
  belongs_to  :shift
end

app/models/day.rb
class Day < ActiveRecord::Base
  attr_accessible :name, :assignment_ids, :shift_ids

  has_many  :assignments
  has_many  :shifts, :through => :assignments

  has_many  :schedules

  has_many  :work_days

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  # Have to make these attributes accessible to insert into join table (employments)
  # Have to have :role_ids to assign roles to an employee 
  attr_accessible :first_name, :last_name, :role_ids, :shift_ids
  #:role_ids, :employee_id,:shift_ids
  
  validates :first_name,  :presence => true
  validates :last_name,   :presence => true

  has_many  :workdays
  has_many  :shifts, :through => :workdays

  has_many  :employments
  has_many  :roles, :through => :employments

 
  def self.elgible_per_shift(shifts)
    
    shift_roles = shifts.map(&:role_ids) 
    shift_names = shifts.map(&:name)
    shift_start_end_times = shifts.map {|shift| [shift.time_start, shift.time_end]}

    elgible_employees = shift_roles.inject([]) do |result, shift_role|
      employees_shuffled = self.elgible_for_shift_by_role( shift_role ).shuffle!
      result << [ employees_shuffled, employees_shuffled[0] ]
      result
    end

    employees_for_shift = shift_names.zip(shift_start_end_times, elgible_employees)

    # Start of code to create nested array that does not have employees double
    # scheduled according to time
    #scheduled_employee = employees_for_shift.map {|shift| shift[2][1] }
    #scheduled_more_than_once = scheduled_employee.map {|employee| employee if scheduled_employee.count(employee) > 1 }.compact.uniq
    #
    #test = []

    #scheduled_employee.each do |employee|
    #  if scheduled_employee.count( employee ) >= 2 
    #    test << scheduled_employee.index( employee.to_s )
    #  end
    #end

    #debugger

    #employees_for_shift
    

  end

  # web-friendly name
  def full_name
    [ self.first_name, self.last_name ].join(" ")
  end

  def days_worked
    self.workdays
  end
  
  private

    # Used as a helper method for self.elgible_per_shift. Returns an array of
    # employees that are elgible to work that shift according to their assigned roles
    def self.elgible_for_shift_by_role(role_ids_for_shift)
      joins(:roles).
      where("roles.id IN(?)", role_ids_for_shift ).
      collect(&:full_name).uniq.sort
    end


end

app/models/employment.rb
class Employment < ActiveRecord::Base

  # Have to make these attributes accesible to insert into join table (employments)
  attr_accessible :employee_id, :role_id

  belongs_to :employee
  belongs_to :role

end

app/models/role.rb
class Role < ActiveRecord::Base

  attr_accessible :name, :employee_ids, :shift_ids
                     
  has_many  :employments
  has_many  :employees, :through => :employments

  has_many  :shiftroles
  has_many  :shifts, :through => :shiftroles
 
  validates :name, :presence => true,
            :uniqueness => true

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

  attr_accessible :schedule_id, :date, :day_id

  belongs_to :day
  has_many   :workdays

  validates :date, :presence => true,
            :uniqueness => true

  # The number of employees who worked this day
  def number_employees_today
    self.workdays.map {|workday| workday.employee_id }.uniq.length
  end

end

app/models/shift.rb
class Shift < ActiveRecord::Base

  # Should have to have :employee_ids to assign employees to a shift
  attr_accessible :name, :time_start, :time_end, :employee_ids, :role_ids
  #attr_accessor :day_of_week_template_name

  has_many  :workdays
  has_many  :employees, :through => :workdays

  has_many  :assignments
  has_many  :days, :through => :assignments

  has_many  :shiftroles
  has_many  :roles, :through => :shiftroles

  validates :name, :presence => true,
            :uniqueness => true
  validates :time_start, :presence => true
  validates :time_end, :presence => true

  # Used to display the role names that are elgible to fill a shift. If empty
  # then print custom message
  def roles_assigned_to_shift( for_print )
    self.roles.empty? ? for_print : self.roles.map { |role| role.name }.join(", ") 
  end

end

app/models/shiftrole.rb
class Shiftrole < ActiveRecord::Base
  
  attr_accessible :shift_id, :role_id

  # The belongs_to in has_many through points to the model name, NOT the table name
  belongs_to :shift
  belongs_to :role
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/workday.rb
class Workday < ActiveRecord::Base
  attr_accessible :employee_id, :shift_id, :schedule_id 

  belongs_to  :employee
  belongs_to  :shift
  belongs_to  :schedule
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
 
  # redirect to root unless user is signed_in
  before_filter :show_page?

  def index
    @days = Day.order("name asc")
  end

  # used to generate a html form for new shift
  def new
    @day = Day.new
  end

  def create
    @day = Day.new(params[:day])

    if @day.save
      flash[:success] = "Day successfully created!"
      redirect_to days_url
    else
      flash[:failure] = "Day NOT created!"
      render :action => 'new'
    end
  end

  def edit
    @day = Day.find(params[:id])
  end

  def update
    
    params[:shift] ||= []

    @day = Day.find(params[:id])

    if @day.update_attributes(params[:day])
      flash[:success] = "Day was updated"
      redirect_to days_url
    else
      flash[:failure] = "Day was NOT updated"
      render 'edit'
    end
  end

  def destroy
    day = Day.find(params[:id]).destroy
    flash[:success] = "Day was destroyed"
    redirect_to days_path
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def dashboard
    @employees = Employee.all
    @roles = Role.all
    @scheduled_days = Schedule.order("date asc")
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  before_filter :show_page?

  def index
    @roles = Role.order('name asc')
  end

  # for html form
  def new
    @role = Role.new(params[:role])
  end

  #  POST => database
  def create
    @role = Role.new(params[:role])

    if @role.save
      flash[:success] = "Role successfully created!"
      redirect_to roles_url
    else
      flash[:failure] = "Role NOT created."
      render 'new'
    end
  end

  # PUT => database
  def update
    @role = Role.find(params[:id])
    if @role.update_attributes(params[:role])
      flash[:success] = "Role successfully updated!"
      redirect_to roles_url
    else
      flash[:failure] = "Role NOT updated."
      render 'new'
    end
  end

  # for html form
  def edit
    @role = Role.find(params[:id])
  end

  def show
    @role = Role.find(params[:id])
  end

  # DELETE => database
  def destroy
    role = Role.find(params[:id]).destroy 
    redirect_to roles_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scheduler</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div id="container">
    <div id="user_nav">
      <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign out", destroy_user_session_path %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </div>
  </div>
  
  <% if user_signed_in? %>
    <ul>
      <li> <%= link_to "Dashboard", root_url %> </li>
      <li> <%= link_to "New Employee", new_employee_url %> </li>
      <li> <%= link_to "Employees", employees_url %></li>
      <li> <%= link_to "New Role", new_role_url %></li>
      <li> <%= link_to "Roles", roles_url %></li>
      <li> <%= link_to "New Shift", new_shift_url %></li>
      <li> <%= link_to "Shifts", shifts_url %></li>
      <li> <%= link_to "New Day Template", new_day_url %></li>
      <li> <%= link_to "Day Templates", days_url %></li>
      <li> <%= link_to "Schedule Day", new_schedule_url %></li>
      <li> <%= link_to "Scheduled Days", schedules_url %></li>
    </ul>
  <% end %>

  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash-#{key}"); %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/pages/dashboard.html.erb
<% if user_signed_in? %>
  <h1>Dashboard</h1>
  <p> Total Employees: <%= pluralize( @employees.count, 'employee' ) %> </p>
  <p> Total Roles: <%= pluralize( @roles.count, 'role') %> </p>
  <table>
    <tr>
      <td>Scheduled Days</td>
      <td></td>
      <td></td>
    </tr>
    <% @scheduled_days.each do |day| %>
    <tr>
      <td><%= link_to day.date, schedule_url(day) %></td>
      <td><%= link_to 'Edit', edit_schedule_url(day) %></td>
      <td><%= link_to 'Delete', day, :method => :delete,
                  :confirm => "Are you sure you want to delete #{ day.date }?"%></td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/shared/_errormessages.html.erb
  <% if object.errors.any? %>
    <div class="errorExplanation">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>